### ISSUE TITLE
Huge hud issue

### ISSUE THREAD

**Issue by khancademy** [Dark-Developments/Zewo2-Addon#1]
There is an issue with the plugin that sometimes makes the players hud.
This can only be fixed by reopening minecraft.
This seems to happen sometimes when opening the modules menu.

**Comment by Nxyi** [comment]
There isnt anything thay should effect the hud within the addon, the only hud element there is, is the example hud element that i forgot to remove. However this shouldnt cause any bugs, if you describe your issue further i might be able to find the cause

**Comment by Eminence5071** [comment]
Whenever i open the modules menu sometimes the hud will break, tho now that im thinking abt it, its probably a meteor bug.
